# Global
FROM einstein42/pgc_nodeserver:beta_node
LABEL maintainer="James Milne <milne.james@gmail.com>"

COPY ecobee/ /app/template
# COPY pgc_interface/pgc_interface /app/pgc_interface
ENTRYPOINT [ "/usr/bin/env", "bash", "-e", "startup.sh" ]